name: paths
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - openslide
  - openslide-python
  - pytorch=2.1.0
  - scikit-learn
  - scikit-survival
  - scikit-image
  - seaborn
  - tqdm
  - torchvision=0.16.0
  - python=3.10
  - pip
  - pip:
      - h5py
      - einops
      - lifelines
      - nystrom-attention
      - opencv-python
      - pandas
      - Pillow
      - tiatoolbox==1.5.1
      - timm==1.0.11
      - torcheval==0.0.7
      - wandb
